spring.application.name=iam

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://localhost:5432/db_iam
spring.datasource.username=postgres
spring.datasource.password=userpostgre

service.iam.token.secret=aWFtX3NlcnZpY2Vfc2VjcmV0X2ZpcnN0X2dlbmVyYXRl
service.iam.token.expiration=600000
service.iam.api-permission.user=/api/v1/accesses/get,/api/v1/requests
service.iam.api-permission.manager=/api/v1/accesses/get,/api/v1/requests/*
service.iam.api-permission.admin=/api/v1/accesses/get,/api/v1/requests/*