BEGIN;
CREATE DATABASE db_iam;

CREATE TABLE "user" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(1000),
    email VARCHAR(255),
    manager_id BIGINT,
    last_updated TIMESTAMP,
    is_blocked BOOLEAN,

    CONSTRAINT fk_user_manager FOREIGN KEY (manager_id) REFERENCES "user"(id)
);

CREATE TABLE login_failed(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    user_id BIGINT not null,
    created_at timestamp,

    CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES "user"(id)
);

CREATE TABLE role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    role_name VARCHAR(100),
    role_desc VARCHAR(1000)
);

CREATE TABLE user_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    last_updated TIMESTAMP,

    CONSTRAINT fk_user_role_user FOREIGN KEY (user_id) REFERENCES "user"(id),
    CONSTRAINT fk_user_role_role FOREIGN KEY (role_id) REFERENCES role(id),
    CONSTRAINT uq_user_role UNIQUE (user_id, role_id)
);

CREATE TABLE access_catalog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    access_name VARCHAR(255),
    base_url VARCHAR(1000),
    created_at TIMESTAMP
);

CREATE TABLE user_access (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    user_id BIGINT NOT NULL,
    access_catalog_id BIGINT NOT NULL,
    created_at TIMESTAMP,
    last_updated TIMESTAMP,

    CONSTRAINT fk_user_access_user FOREIGN KEY (user_id) REFERENCES "user"(id),
    CONSTRAINT fk_user_access_access_catalog FOREIGN KEY (access_catalog_id) REFERENCES access_catalog(id),
    CONSTRAINT uq_user_access UNIQUE (user_id, access_catalog_id)
);

CREATE TABLE request_access (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    status VARCHAR(100),
    assign_to_user BIGINT,
    assign_to_role BIGINT NOT NULL,
    updated_by BIGINT,
    last_updated TIMESTAMP,

    CONSTRAINT fk_request_access_assign_user FOREIGN KEY (assign_to_user) REFERENCES "user"(id),
    CONSTRAINT fk_request_access_assign_role FOREIGN KEY (assign_to_role) REFERENCES role(id)
);

CREATE TABLE request_access_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    request_access_id BIGINT NOT NULL,
    old_access_catalog TEXT,
    new_access_catalog TEXT,
    status VARCHAR(100),
    assign_to_user BIGINT,
    assign_to_role BIGINT NOT NULL,
    updated_by BIGINT,
    updated_at TIMESTAMP,

    CONSTRAINT fk_request_access_history_request FOREIGN KEY (request_access_id) REFERENCES request_access(id),
    CONSTRAINT fk_request_access_history_assign_user FOREIGN KEY (assign_to_user) REFERENCES "user"(id),
    CONSTRAINT fk_request_access_history_assign_role FOREIGN KEY (assign_to_role) REFERENCES role(id)
);

CREATE TABLE request_access_detail (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    request_access_id BIGINT NOT NULL,
    access_catalog_id BIGINT NOT NULL,
    action VARCHAR(25),

    CONSTRAINT fk_request_access_detail_request FOREIGN KEY (request_access_id) REFERENCES request_access(id),
    CONSTRAINT fk_request_access_detail_access_catalog FOREIGN KEY (access_catalog_id) REFERENCES access_catalog(id)
);
END;